[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.3.2",
    "fastapi[standard]>=0.115.8",
    "openai>=1.64.0",
    "pandas>=2.0.0",
    "python-multipart>=0.0.6",
]
